### ISSUE TITLE
current-property cannot be used in nested function call

### ISSUE THREAD

**Issue by ghost** [stylus/stylus#1351]
Example:

```
m1()
  m2()
m2()
  current-property[0]
test
  prop: m1()
```

Results in:

```
RangeError: Maximum stylus call stack size exceeded
    at Evaluator.visitCall (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:509:11)
    at Evaluator.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitExpression (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:661:26)
    at Evaluator.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitExpression (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:661:26)
    at Evaluator.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitIdent (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:565:23)
```

But it works when using the m2 function directly

**Comment by Phroneris** [comment]
Th-this has been left unfixed for over a decade!? Really!?

It seems that depending on the nesting depth $d$ ($= 2$ in @ghost's example), the length of `called-from` list becomes $dn - 1$ during the $n$-th (1-based) iteration.
And particularly when $n \geq 2$, the root function's name appears in that list.

```stylus
d0()
  p(unquote("called-from:") called-from)
  current-property
d1()
  d0()
d2()
  d1()

test
  prop: d0() // edit here: d0-d2

// prop: d0():
//   console:
//     inspect: called-from: ()
//   result:
//     test {
//       prop: 'prop' __CALL__;
//     }

// prop: d1():
//   console:
//     inspect: called-from: (d1)
//     inspect: called-from: (d1 d0 d1)
//     inspect: called-from: (d1 d0 d1 d0 d1)
//     inspect: called-from: (d1 d0 d1 d0 d1 d0 d1)
//     inspect: called-from: (d1 d0 d1 d0 d1 d0 d1 d0 d1)
//     ...
//     Maximum stylus call stack size exceeded

// prop: d2():
//   console:
//     inspect: called-from: (d1 d2)
//     inspect: called-from: (d1 d2 d0 d1 d2)
//     inspect: called-from: (d1 d2 d0 d1 d2 d0 d1 d2)
//     inspect: called-from: (d1 d2 d0 d1 d2 d0 d1 d2 d0 d1 d2)
//     inspect: called-from: (d1 d2 d0 d1 d2 d0 d1 d2 d0 d1 d2 d0 d1 d2)
//     ...
//     Maximum stylus call stack size exceeded
```

The workaround I found is adding `return if index(called-from, "root-function-name") != null` before using `current-property` in the root function so that the total number of loops can be reduced from infinite to 2.

```stylus
d0()
  p(unquote("called-from:") called-from)
  return if index(called-from, "d0") != null // added
  current-property
d1()
  d0()
d2()
  d1()

test
  prop: d0() // edit here: d0-d2

// prop: d0():
//   console:
//     inspect: called-from: ()
//   result:
//     test {
//       prop: 'prop' __CALL__;
//     }

// prop: d1():
//   console:
//     inspect: called-from: (d1)
//     inspect: called-from: (d1 d0 d1)
//   result:
//     test {
//       prop: 'prop';
//     }

// prop: d2():
//   console:
//     inspect: called-from: (d1 d2)
//     inspect: called-from: (d1 d2 d0 d1 d2)
//   result:
//     test {
//       prop: 'prop';
//     }
```

Ideally it should be 1 of course, but since the recursion occurs at the moment when `current-property` is used, it seems difficult to resolve this further with Stylus code.
I look forward to the day this is fixed fundamentally.

My environment:

- Stylus: 0.64.0
- Node.js: 24.8.0
- Terminal: GNU bash, version 5.2.37(1)-release (x86_64-pc-msys)
  - by Git for Windows 2.49.0
- OS: Windows 10 64-bit 22H2
- Region/Language: Japan/Japanese

**Comment by Phroneris** [comment]
Oh, I need to update my example:

- Early `return` should return `__CALL__` rather than nothing (`null`) for better emulation
- The `in` operator is more handy than `index() != null`
- (Added argument handling just for extra demo)

```stylus
d0()
  p(unquote("arguments:") arguments)
  p(unquote("called-from:") called-from)
  return __CALL__ if "d0" in called-from // here are two core updates!
  return unquote("(") current-property arguments unquote(")")
d1()
  d0(arguments)
d2()
  d1(arguments)

test
  prop0: x0 d0(y0) z0
  prop1: x1 d1(y1) z1
  prop2: x2 d2(y2) z2

// console:
//   inspect: arguments: (y0)
//   inspect: called-from: ()
//   inspect: arguments: (y1)
//   inspect: called-from: (d1)
//   inspect: arguments: (y1)
//   inspect: called-from: (d1 d0 d1)
//   inspect: arguments: (y2)
//   inspect: called-from: (d1 d2)
//   inspect: arguments: (y2)
//   inspect: called-from: (d1 d2 d0 d1 d2)
// result:
//   test {
//     prop0: x0 ( 'prop0' x0 __CALL__ z0 y0 ) z0;
//     prop1: x1 ( 'prop1' x1 __CALL__ z1 y1 ) z1;
//     prop2: x2 ( 'prop2' x2 __CALL__ z2 y2 ) z2;
//   }
```
