### ISSUE TITLE
Can't escape special characters in strings

### ISSUE THREAD

**Issue by ysulyma** [stylus/stylus#1522]
test.styl

```
blockquote::before
  content "\""
```

Command: `stylus -p test.styl`

Expected output

```
blockquote::before {
  content: "a";
}
```

Actual Output

```
node_modules/stylus/bin/stylus:540
              throw err;
                    ^
ParseError: test.styl:2
   1| blockquote::before
 > 2|   content "\""
   3|

expected "indent", got "outdent"

    at Parser.error (node_modules/stylus/lib/parser.js:166:11)
    at Parser.expect (node_modules/stylus/lib/parser.js:194:12)
    at Parser.block (node_modules/stylus/lib/parser.js:606:12)
    at Parser.selector (node_modules/stylus/lib/parser.js:1090:24)
    at Parser.property (node_modules/stylus/lib/parser.js:1041:47)
    at Parser.ident (node_modules/stylus/lib/parser.js:998:25)
    at Parser.stmt (node_modules/stylus/lib/parser.js:555:26)
    at Parser.statement (node_modules/stylus/lib/parser.js:465:21)
    at Parser.block (node_modules/stylus/lib/parser.js:618:21)
    at Parser.selector (node_modules/stylus/lib/parser.js:1090:24)
```

The same thing occurs with `content '\''`.

**Comment by wildeyes** [comment]
With stylus 0.54.5, I'm getting for `content: '\uASDF'` -> `content: 'uASDF'`.

**Comment by Panya** [comment]
@wildeyes cannot reproduce, see http://stylus-lang.com/try.html#?code=body%20%7B%0A%20%20content%3A%20'%5CuASDF'%0A%7D
