### ISSUE TITLE
Bug with calling a function from a hash object

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1690]
While you can store functions in objects, you cannot call them straight away:

```
foo = {
  bar: @(){
    width: 10px
  }
}

.foo
  foo.bar()
```

throws

```
ParseError: test.styl:9:11
    5| }
    6|
    7|
    8| .foo
    9|   foo.bar()
----------------^

expected "indent", got "outdent"

    at Parser.error (/Users/kizu/Projects/stylus/lib/parser.js:257:11)
    at Parser.expect (/Users/kizu/Projects/stylus/lib/parser.js:285:12)
    at Parser.block (/Users/kizu/Projects/stylus/lib/parser.js:820:12)
    at Parser.selector (/Users/kizu/Projects/stylus/lib/parser.js:1420:24)
    at Parser.stmt (/Users/kizu/Projects/stylus/lib/parser.js:777:27)
    at Parser.statement (/Users/kizu/Projects/stylus/lib/parser.js:667:21)
    at Parser.block (/Users/kizu/Projects/stylus/lib/parser.js:832:21)
    at Parser.selector (/Users/kizu/Projects/stylus/lib/parser.js:1420:24)
    at Parser.stmt (/Users/kizu/Projects/stylus/lib/parser.js:777:27)
    at Parser.statement (/Users/kizu/Projects/stylus/lib/parser.js:667:21)
```

The same for `foo['bar']()` syntax.

As a workaround we can save the function to var:

```
  bar = foo.bar
  bar()
```

But it would be really nice to be able to use those “methods” right from the object.

**Comment by bloadvenro** [comment]
+1

**Comment by Yska** [comment]
Are there any updates?
