### ISSUE TITLE
Block commenting selectors throws ParseError

### ISSUE THREAD

**Issue by garthkerr** [stylus/stylus#1889]
Starting with version `0.50.0` block commenting a selector throws an error:
``` stylus
.test
  /*.test*/
    /*padding 60px*/
```
```
ParseError: test.styl:9:21
    5|  */
    6|
    7| .test
    8|   /*.test*/
    9|     /*padding 60px*/
--------------------------^
   10|

unexpected "indent"

    at Parser.error (/usr/lib/node_modules/stylus/lib/parser.js:257:11)
    at Parser.stmt (/usr/lib/node_modules/stylus/lib/parser.js:798:32)
    at Parser.statement (/usr/lib/node_modules/stylus/lib/parser.js:669:21)
    at Parser.block (/usr/lib/node_modules/stylus/lib/parser.js:840:21)
    at Parser.selector (/usr/lib/node_modules/stylus/lib/parser.js:1524:24)
    at Parser.stmt (/usr/lib/node_modules/stylus/lib/parser.js:780:27)
    at Parser.statement (/usr/lib/node_modules/stylus/lib/parser.js:669:21)
    at Parser.parse (/usr/lib/node_modules/stylus/lib/parser.js:234:25)
    at Evaluator.importFile (/usr/lib/node_modules/stylus/lib/visitor/evaluator.js:73:20)
    at Evaluator.visitImport (/usr/lib/node_modules/stylus/lib/visitor/evaluator.js:902:27)
```

Block commenting ONLY properties works fine:
``` stylus
.test
  .test
    /*padding 60px*/
```

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.

**Comment by garthkerr** [comment]
Thank you for the quick response.
