### ISSUE TITLE
Comments can cause indentation error

### ISSUE THREAD

**Issue by ajnisbet** [stylus/stylus#1934]
When I run stylus (v0.51.1) on the following file
```stylus
.row
  color #eee
  //   strong
    //   height 1px
    //   color #fff
```

I get this indent error:

```
/usr/lib/node_modules/stylus/bin/stylus:661
              throw err;
                    ^
ParseError: test.styl:5:5
   1| .row
   2|   color #eee
   3|   //   strong
   4|     //   height 1px
   5|     //   color #fff
----------^

unexpected "indent"

    at Parser.error (/usr/lib/node_modules/stylus/lib/parser.js:257:11)
    at Parser.stmt (/usr/lib/node_modules/stylus/lib/parser.js:798:32)
    at Parser.statement (/usr/lib/node_modules/stylus/lib/parser.js:669:21)
    at Parser.block (/usr/lib/node_modules/stylus/lib/parser.js:842:21)
    at Parser.selector (/usr/lib/node_modules/stylus/lib/parser.js:1529:24)
    at Parser.stmt (/usr/lib/node_modules/stylus/lib/parser.js:780:27)
    at Parser.statement (/usr/lib/node_modules/stylus/lib/parser.js:669:21)
    at Parser.parse (/usr/lib/node_modules/stylus/lib/parser.js:234:25)
    at Renderer.render (/usr/lib/node_modules/stylus/lib/renderer.js:80:22)
    at /usr/lib/node_modules/stylus/bin/stylus:655:15
```
It comes up fairly frequently when using a text editor to comment code. Removing the comments fixes the error.

I can't figure out the pattern for problematic comments, removing any one comment line from the above example also fixes the error.

Because lines containing only comments aren't included in the rendered CSS, I expected stylus to ignore those lines before inferring any indentation logic. Otherwise, perhaps it should be documented in https://learnboost.github.io/stylus/docs/comments.html?

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
