### ISSUE TITLE
Bug when there is no whitespace between keyframes name and the following curly brace

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#1945]
``` styl
@keyframes foo{0%{bar:baz}}
```

gives an error:

```
ParseError: test.styl:1:28
   1| @keyframes foo{0%{bar:baz}}
---------------------------------^

expected "indent", got "eos"

    at Parser.error (/Users/kizu/Projects/stylus/lib/parser.js:257:11)
    at Parser.expect (/Users/kizu/Projects/stylus/lib/parser.js:285:12)
    at Parser.block (/Users/kizu/Projects/stylus/lib/parser.js:829:12)
    at Parser.keyframes (/Users/kizu/Projects/stylus/lib/parser.js:1305:28)
    at Parser.stmt (/Users/kizu/Projects/stylus/lib/parser.js:747:21)
    at Parser.statement (/Users/kizu/Projects/stylus/lib/parser.js:674:21)
    at Parser.parse (/Users/kizu/Projects/stylus/lib/parser.js:234:25)
    at Renderer.render (/Users/kizu/Projects/stylus/lib/renderer.js:80:22)
    at /Users/kizu/Projects/stylus/bin/stylus:655:15
    at fs.js:266:14
```

while when there is at least a space it renders ok:

``` styl
@keyframes foo {0%{bar:baz}}
```

**Comment by Panya** [comment]
Thanks for the report. I've fixed this bug in the `dev` branch. The fix will be in the next release.
