### ISSUE TITLE
"alpha" argument required

### ISSUE THREAD

**Issue by yutiya** [stylus/stylus#1966]
Follow Example:
body
		color: hue(hsla(50deg, 100%, 80%))

Result:
```
Error: stylus:2:35
   1| body
   2|   color: hue(hsla(50deg, 100%, 80%))
----------------------------------------^

"alpha" argument required
    at "body" (stylus:2:1)

    at Object.exports.assertPresent (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/utils.js:267:19)
    at Object.exports.assertType (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/utils.js:204:11)
    at Evaluator.hsla (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/functions/index.js:99:13)
    at Evaluator.invokeBuiltin (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/visitor/evaluator.js:1037:30)
    at Evaluator.visitCall (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/visitor/evaluator.js:502:16)
    at Evaluator.Visitor.visit (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/visitor/evaluator.js:156:18)
    at Evaluator.visitExpression (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/visitor/evaluator.js:630:26)
    at Evaluator.Visitor.visit (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/admin/Desktop/nodejs-stylus/node_modules/stylus/lib/visitor/evaluator.js:156:18)
```

**Comment by Panya** [comment]
The error message is very clear: `hsla` function requires 4 arguments (hue, saturation and lightness), but you pass only 3. The alpha value is missing.

**Comment by yutiya** [comment]
Yes, document have error! need update

**Comment by Panya** [comment]
I've already updated the docs. Thanks for the report.
