### ISSUE TITLE
Parse error on @font-face

### ISSUE THREAD

**Issue by blond** [stylus/stylus#1971]
Stylus version `0.52.0`.

I have `styles/font.styl` file with `@font-face`:

```styl
@font-face
{
    font-family: 'ekibastuzregular';
}
```

If you try to compile this file with `stylus`:

```
$ stylus < styles/font.styl > index.css
```

Then you get the error:

```
/Users/blond/projects/stylus-bug/node_modules/stylus/bin/stylus:593
      if (err) throw err;
                     ^
TypeError: stdin:5:1
   1| @font-face
   2| {
   3|     font-family: "ekibastuzregular";
   4| }
   5|
------^

Cannot read property 'block' of undefined

    at Group.block (/Users/blond/projects/stylus-bug/node_modules/stylus/lib/nodes/group.js:48:23)
    at Group.clone (/Users/blond/projects/stylus-bug/node_modules/stylus/lib/nodes/group.js:90:21)
    at /Users/blond/projects/stylus-bug/node_modules/stylus/lib/nodes/root.js:65:21
    at Array.forEach (native)
    at Root.clone (/Users/blond/projects/stylus-bug/node_modules/stylus/lib/nodes/root.js:64:14)
    at MemoryCache.set (/Users/blond/projects/stylus-bug/node_modules/stylus/lib/cache/memory.js:25:21)
    at Parser.parse (/Users/blond/projects/stylus-bug/node_modules/stylus/lib/parser.js:239:20)
    at Renderer.render (/Users/blond/projects/stylus-bug/node_modules/stylus/lib/renderer.js:80:22)
    at ReadStream.<anonymous> (/Users/blond/projects/stylus-bug/node_modules/stylus/bin/stylus:592:11)
    at ReadStream.emit (events.js:129:20)
```

**Comment by tadatuta** [comment]
+1

**Comment by scf2k** [comment]
+1

**Comment by sipayRT** [comment]
+1

But you can use hack until this issue will be down:

```
@font-face {
    font-family: "ekibastuzregular";
}
```

**Comment by eGavr** [comment]
@blond :+1:

**Comment by SwinX** [comment]
:+1:

**Comment by Panya** [comment]
I've fixed this bug in the `dev` branch. Thanks for the report.

**Comment by blond** [comment]
@Panya Thanks!
