### ISSUE TITLE
JavaScript API not working.

### ISSUE THREAD

**Issue by JoshuaWise** [stylus/stylus#1989]
I'm able to compile my `test.styl` file with the globally install command line tool. 

But I get an error when I try this:
```javascript
var input = require('fs').readFileSync('test.styl');
require('stylus')(input).render(function(err, css) {
    if (err) throw err;
    console.log('success!');
});
```

Here's the error:
```
TypeError: undefined is not a function
    at Object.Lexer (/path/to/project/node_modules/stylus/lib/lexer.js:91:23)
    at new Parser (/path/to/project/node_modules/stylus/lib/parser.js:156:18)
    at Renderer.render (/path/to/project/node_modules/stylus/lib/renderer.js:70:30)
    at repl:1:40
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
```

Any ideas?

**Comment by JoshuaWise** [comment]
Never mind, I was passing a Buffer, instead of a string, to stylus.
I recommend Buffers be automatically be converted to strings, since I assume that is so common.
