### ISSUE TITLE
Bug with hash assignment inside loops/conditions

### ISSUE THREAD

**Issue by kizu** [stylus/stylus#2075]
``` styl
$foo = {
  a: b
}
$bar = {
  baz: {}
}
for $key, $value in $foo
  $bar.baz[$key] = $value
```

throws

```
ParseError: test.styl:9:1
    5|   baz: {}
    6| }
    7| for $key, $value in $foo
    8|   $bar.baz[$key] = $value
    9|
------^

expected "indent", got "outdent"

    at Parser.error (/Users/kizu/Projects/stylus/lib/parser.js:259:11)
    at Parser.expect (/Users/kizu/Projects/stylus/lib/parser.js:287:12)
    at Parser.block (/Users/kizu/Projects/stylus/lib/parser.js:845:12)
    at Parser.selector (/Users/kizu/Projects/stylus/lib/parser.js:1555:24)
    at Parser.ident (/Users/kizu/Projects/stylus/lib/parser.js:1380:23)
    at Parser.stmt (/Users/kizu/Projects/stylus/lib/parser.js:778:26)
    at Parser.statement (/Users/kizu/Projects/stylus/lib/parser.js:685:21)
    at Parser.block (/Users/kizu/Projects/stylus/lib/parser.js:865:21)
    at Parser [as for] (/Users/kizu/Projects/stylus/lib/parser.js:910:23)
    at Parser.stmt (/Users/kizu/Projects/stylus/lib/parser.js:778:26)
```

Similar stuff happens when there is `if` instead of `for` and when used with `['baz']` instead of `.baz`

``` styl
$foo = {
  a: b
}
$bar = {
  baz: {}
}
for $key, $value in $foo
  $bar['baz'][$key] = $value
```

it throws another error:

```
TypeError: test.styl:9:1
    5|   baz: {}
    6| }
    7| for $key, $value in $foo
    8|   $bar['baz'][$key] = $value
    9|
------^

Cannot call method 'clone' of undefined

    at BinOp.clone (/Users/kizu/Projects/stylus/lib/nodes/binop.js:45:26)
    at BinOp.clone (/Users/kizu/Projects/stylus/lib/nodes/binop.js:45:26)
    at /Users/kizu/Projects/stylus/lib/nodes/expression.js:86:17
    at Array.map (native)
    at Expression.clone (/Users/kizu/Projects/stylus/lib/nodes/expression.js:85:28)
    at Property.clone (/Users/kizu/Projects/stylus/lib/nodes/property.js:49:41)
    at /Users/kizu/Projects/stylus/lib/nodes/block.js:93:21
    at Array.forEach (native)
    at Block.clone (/Users/kizu/Projects/stylus/lib/nodes/block.js:92:14)
    at Each.clone (/Users/kizu/Projects/stylus/lib/nodes/each.js:50:28)
```

**Comment by JasonWoof** [comment]
WORKAROUND: the first error is triggered only when you mix the ``.foo`` syntax with the ``['foo']`` syntax, eg "bar.foo['foo']". So, change that to ``bar.foo.foo`` or ``bar['foo']['foo']``

Your 2nd error, I think is because b is undefined

**Comment by JasonWoof** [comment]
There are two bugs here.

One is #2076 

The other is triggered by assignments inside loops. Here's teh simplest test case for the latter that I've been able to come up with:

	error("If you get this error, then the parsed")
	for k, v in hash
		hash[k]['foo'] = 'bar'

For this I get the "Cannot call method 'clone' of undefined" error, just like the @kizu
