### ISSUE TITLE
syntax errors from assigning to hashes using brackets and dots

### ISSUE THREAD

**Issue by JasonWoof** [stylus/stylus#2076]
I'm getting syntax errors when I try to change a value in a nested hash iff I use the ["foo"] syntax for the outer hash and the .propname syntax for the inner hash (or vice versa). If I use brackets for both or dots for both, it works fine.

Example code:

	main()
		foo = {
			a: {
				b: 20px
			}
		}

		// try un-commenting one of the following lines:
		// foo["a"].b = 10px    // syntax error
		// foo["a"]['b'] = 10px // works
		// foo.a['b'] = 10px    // syntax error
		// foo.a.b = 10px       // works

		return foo.a.b // syntax error blames this line
		// saying: expected "indent", got "return"

	body
		font-size: main()

Error from uncommenting first line marked "syntax error":

	/home/jasonwoof/software/stylus/bin/stylus:593
      	  if (err) throw err;
               	   ^
	ParseError: stdin:14:9
   	   10|  // foo["a"]['b'] = 10px // works
   	   11|  // foo.a['b'] = 10px    // syntax error
   	   12|  // foo.a.b = 10px       // works
   	   13|
   	   14|  return foo.a.b // syntax error blames this line
	---------------^
   	   15|  // saying: expected "indent", got "return"
   	   16|
   	   17| body

	expected "indent", got "return"

    	at Parser.error (/home/jasonwoof/software/stylus/lib/parser.js:259:11)
    	at Parser.expect (/home/jasonwoof/software/stylus/lib/parser.js:287:12)
    	at Parser.block (/home/jasonwoof/software/stylus/lib/parser.js:845:12)
    	at Parser.selector (/home/jasonwoof/software/stylus/lib/parser.js:1555:24)
    	at Parser.ident (/home/jasonwoof/software/stylus/lib/parser.js:1392:23)
    	at Parser.stmt (/home/jasonwoof/software/stylus/lib/parser.js:778:26)
    	at Parser.statement (/home/jasonwoof/software/stylus/lib/parser.js:685:21)
    	at Parser.block (/home/jasonwoof/software/stylus/lib/parser.js:865:21)
    	at Parser.functionDefinition (/home/jasonwoof/software/stylus/lib/parser.js:1745:21)
    	at Parser.function (/home/jasonwoof/software/stylus/lib/parser.js:1686:18)

error for the other line marked "syntax error" gives basically the same results (including blaming the "return" line)

The above error/backtrace is from stylus 0.53.0 from this repo.

I get basically the same thing from stylus 0.48.1 from debian.

**Comment by Panya** [comment]
Seems the same problem as in #2075. I'm closing it as a duplicate.
