### ISSUE TITLE
Stylus fails to compile file in script mode only

### ISSUE THREAD

**Issue by blitzprog** [stylus/stylus#2112]
I'm getting lots of these errors when running node with `--use_strict`:

```
ReferenceError: stylus:156:16
   152| 		width 100%
   153| 		text-align center
   154| 
   155| 	.summary-header
   156| 		display block
-----------------------^

child is not defined
```

```
child is not defined

    at parse (/home/eduard/projects/aero2/node_modules/stylus/lib/utils.js:465:15)
    at /home/eduard/projects/aero2/node_modules/stylus/lib/utils.js:492:19
    at Array.forEach (native)
    at compile (/home/eduard/projects/aero2/node_modules/stylus/lib/utils.js:490:14)
    at /home/eduard/projects/aero2/node_modules/stylus/lib/utils.js:483:11
    at Array.forEach (native)
    at compile (/home/eduard/projects/aero2/node_modules/stylus/lib/utils.js:479:14)
    at Object.exports.compileSelectors (/home/eduard/projects/aero2/node_modules/stylus/lib/utils.js:498:3)
    at Normalizer.visitGroup (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/normalizer.js:270:25)
    at Normalizer.Visitor.visit (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/index.js:28:40)
    at Normalizer.visitBlock (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/normalizer.js:232:27)
    at Normalizer.Visitor.visit (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/index.js:28:40)
    at Normalizer.extend (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/normalizer.js:423:22)
    at Normalizer.visitGroup (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/normalizer.js:279:8)
    at Normalizer.Visitor.visit (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/index.js:28:40)
    at Normalizer.visitRoot (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/normalizer.js:170:23)
    at Normalizer.Visitor.visit (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/index.js:28:40)
    at Normalizer.normalize (/home/eduard/projects/aero2/node_modules/stylus/lib/visitor/normalizer.js:53:18)
    at Renderer.render (/home/eduard/projects/aero2/node_modules/stylus/lib/renderer.js:90:22)
    at Renderer.tryCatcher (/home/eduard/projects/aero2/node_modules/bluebird/js/release/util.js:11:23)
    at ret (eval at <anonymous> (/home/eduard/projects/aero2/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Aero.module.exports (/home/eduard/projects/aero2/lib/Aero/loadStyle.js:14:16)
    at next (native)
    at tryCatcher (/home/eduard/projects/aero2/node_modules/bluebird/js/release/util.js:11:23)
    at PromiseSpawn._promiseFulfilled (/home/eduard/projects/aero2/node_modules/bluebird/js/release/generators.js:90:49)
    at Promise._settlePromise (/home/eduard/projects/aero2/node_modules/bluebird/js/release/promise.js:553:26)
    at Promise._settlePromise0 (/home/eduard/projects/aero2/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/home/eduard/projects/aero2/node_modules/bluebird/js/release/promise.js:676:18)
```

I'll add more details and ways to reproduce it later.

**Comment by Panya** [comment]
Already fixed in the `dev` branch.

**Comment by blitzprog** [comment]
Ah, thank you for the info @Panya, looking forward to it!
