### ISSUE TITLE
 stylus <directory> does not seem to work

### ISSUE THREAD

**Issue by adius** [stylus/stylus#2173]
In the documentation at http://stylus-lang.com/docs/executable.html
it's described that `stylus css` compiles all files in the directory.
But I get following error:

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at extname (path.js:1429:5)
    at createPath (/Users/adrian/Projects/bitcoinate/bitcoinate.org/node_modules/stylus/bin/stylus:692:29)
    at writeFile (/Users/adrian/Projects/bitcoinate/bitcoinate.org/node_modules/stylus/bin/stylus:705:14)
    at Array.<anonymous> (/Users/adrian/Projects/bitcoinate/bitcoinate.org/node_modules/stylus/bin/stylus:664:13)
    at Renderer.render (/Users/adrian/Projects/bitcoinate/bitcoinate.org/node_modules/stylus/lib/renderer.js:114:27)
    at /Users/adrian/Projects/bitcoinate/bitcoinate.org/node_modules/stylus/bin/stylus:655:15
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

When I use `stylus css --out css` everything works as expected

**Comment by Panya** [comment]
I guess you're using Node 6.0, Stylus is not fully compatible with it at this moment. I'll fix it as soon as possible.

**Comment by adius** [comment]
Ah ok. Yeah, with improved es2015 support I had to upgrade immediately to 0.6.0 =)
