### ISSUE TITLE
Broken in Node.js v6.0.0

### ISSUE THREAD

**Issue by adambiggs** [stylus/stylus#2176]
After updating Node.js to v6.0.0, my `gulp-stylus` tasks started failing with the following errors:

Before the gulp task starts...
```
(node:92717) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

The error...
```
TypeError: /path/to/my/project/styles/main.styl:34:1
   30| @import 'users'
   31| @import 'libs'
   32|
-------^

Path must be a string. Received undefined

  at assertPath (path.js:7:11)
  at extname (path.js:1429:5)
  at new SourceMapper (/path/to/my/project/node_modules/stylus/lib/visitor/sourcemapper.js:41:7)
  at Renderer.render (/path/to/my/project/node_modules/stylus/lib/renderer.js:94:9)
  at dispatch (/path/to/my/project/node_modules/when/node.js:71:15)
  at callAndResolve (/path/to/my/project/node_modules/when/lib/apply.js:30:12)
  at apply (/path/to/my/project/node_modules/when/lib/apply.js:23:4)
  at Object.call (/path/to/my/project/node_modules/when/node.js:107:10)
  at Stylus._render (/path/to/my/project/node_modules/accord/lib/adapters/stylus/0.x.js:105:21)
```

After rolling back to Node.js v5.11.0, the error no longer occurs.

**Comment by Panya** [comment]
It's already fixed in Stylus 0.54.3+. Try to update `gulp-stylus`...

**Comment by adambiggs** [comment]
Weird, I confirmed that i'm using the latest version of `gulp-stylus`, and ran `$ npm update` before opening this issue, but my `stylus` version was still at an old version...

But after running `$ rm -rf node_modules && npm install`, everything is now working in Node v6.

**Comment by QuantumInformation** [comment]
I still get this issue.
