### ISSUE TITLE
Array addressing with variables only works in last position

### ISSUE THREAD

**Issue by MatejJan** [stylus/stylus#2233]
Hi, this is a very specific bug I found. Here is a minimal reproduction:

```
a = (#000 #111), (#222 #333)

b = 0
c = 1

body
  color a[1][b]
  background a[1][1]
```

The problem is when variable `b` appears anywhere but the last position. So if I use:
```
body
  color a[b][1]
  background a[1][1]
```
or
```
body
  color a[1][1]
  background a[b][1]
```
It still won't work.

However, in the last position as in:
```
a = (#000 #111), (#222 #333)

b = 0
c = 1

body
  color a[1][1]
  background a[1][b]
```
This works fine.

It also doesn't work if there is another property after:
```
body
  color a[1][1]
  background a[1][b]
  border 1px
```

The crash stacktrace is:
```
Matejs-MacBook-Pro:Desktop Retro$ stylus test.styl 

/usr/local/lib/node_modules/stylus/bin/stylus:662
              throw err;
              ^
ParseError: test.styl:9:1
    5| 
    6| body
    7|   color a[1][b]
    8|   background a[1][1]
    9| 
------^

expected "indent", got "outdent"

    at Parser.error (/usr/local/lib/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (/usr/local/lib/node_modules/stylus/lib/parser.js:287:12)
    at Parser.block (/usr/local/lib/node_modules/stylus/lib/parser.js:845:12)
    at Parser.selector (/usr/local/lib/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.property (/usr/local/lib/node_modules/stylus/lib/parser.js:1498:51)
    at Parser.ident (/usr/local/lib/node_modules/stylus/lib/parser.js:1453:25)
    at Parser.stmt (/usr/local/lib/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (/usr/local/lib/node_modules/stylus/lib/parser.js:685:21)
    at Parser.block (/usr/local/lib/node_modules/stylus/lib/parser.js:865:21)
    at Parser.selector (/usr/local/lib/node_modules/stylus/lib/parser.js:1555:24)
```

And in the working case, the css gets correctly generated into:
```
body {
  color: #333;
  background: #222;
}
```

**Comment by MatejJan** [comment]
Here's a possible workaround in the mean time. 

For example, this doesn't work:
```
a = (#000 #111), (#222 #333)

f(i,j)
  a[i][j]

body
  color f(1,1)
```

But you can rewrite it as:
```
a = (#000 #111), (#222 #333)

f(i,j)
  temp = a[i]
  temp[j]

body
  color f(1,1)
```

**Comment by Panya** [comment]
Stylus thinks that it's a nested selector. As a temporary workaround you can write `:` after property names:
```styl
a = (#000 #111), (#222 #333)

b = 0
c = 1

body
  color: a[1][b]
  background: a[1][1]
```

**Comment by MatejJan** [comment]
Ah, I see. How about in the function case above in my own workaround post?

**Comment by Panya** [comment]
Well, the same problem. You can tell Stylus that it's not a selector in a mixin by returning the value with `return`.
```styl
a = (#000 #111), (#222 #333)

f(i,j)
  return a[i][j]

body
  color f(1,1)
```

**Comment by MatejJan** [comment]
That is just what I needed! Somehow I wasn't aware of `return`. And thank you for very fast responses.
