### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by bkjohnson** [stylus/stylus#2240]
I apologize if there is already an answer to this, but I didn't find it.  I cloned the repository in order to try to make some changes and I can't get it to build.  When I run `make` I get this:

```
  227 passing (52s)
  1 failing

  1) integration prefix grid:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
  ```

If I just run `npm run test` I get this:
```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! stylus@0.54.5 test: `mocha test/ test/middleware/ --require should --bail --check-leaks --reporter dot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the stylus@0.54.5 test script 'mocha test/ test/middleware/ --require should --bail --check-leaks --reporter dot'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the stylus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha test/ test/middleware/ --require should --bail --check-leaks --reporter dot
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs stylus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls stylus
npm ERR! There is likely additional logging output above.
```

And finally, here are the verbose lines from npm-debug.log

```
14 verbose stack Error: stylus@0.54.5 test: `mocha test/ test/middleware/ --require should --bail --check-leaks --reporter dot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Does anyone know what is going on here?  I haven't made any changes other than a few logging statements, so I think there is something messed up with my setup.

**Comment by PalleZingmark** [comment]
Do you still get the same error if you increase the timeout by adding `--timeout 15000` to the call?

**Comment by iChenLei** [comment]
solved
