### ISSUE TITLE
Can i use variable by rgba argument?

### ISSUE THREAD

**Issue by syuilo** [stylus/stylus#2259]
Version: 0.54.5

```
Error: C:\Users\syuilo\Desktop\projects\misskey\misskey-web\src\base.styl:10:44
    6|  background $theme-color
    7|  color #fff
    8|
    9| *
   10|  tap-highlight-color rgba($theme-color, 0.7)
--------------------------------------------------^
   11|
   12| html, body
   13|  margin 0

TypeError: expected rgba or hsla, but got string:'#f76d6c'
    at "*" (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\src\base.styl:8:12)

    at Object.exports.assertColor (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\utils.js:255:13)
    at Evaluator.rgba (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\functions\rgba.js:32:13)
    at Evaluator.invokeBuiltin (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:1051:30)
    at Evaluator.visitCall (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:516:16)
    at Evaluator.Visitor.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitProperty (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:687:22)
    at Evaluator.Visitor.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Evaluator.Visitor.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitGroup (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:261:22)
    at Evaluator.Visitor.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitRoot (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at Evaluator.Visitor.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.evaluate (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\visitor\evaluator.js:247:15)
    at Renderer.render (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\stylus\lib\renderer.js:86:26)
    at dispatch (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\when\node.js:71:15)
    at callAndResolve (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\when\lib\apply.js:30:12)
    at apply (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\when\lib\apply.js:23:4)
    at Object.call (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\when\node.js:107:10)
    at Stylus._render (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\accord\lib\adapters\stylus\0.x.js:105:21)
    at Stylus.Adapter.render (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\accord\lib\adapter_base.js:124:19)
    at DestroyableTransform._transform (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\gulp-stylus\index.js:37:12)
    at DestroyableTransform.Transform._read (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\readable-stream\lib\_stream_writable.js:347:64)
    at writeOrBuffer (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\readable-stream\lib\_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\readable-stream\lib\_stream_writable.js:274:11)
    at write (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\through2\through2.js:26:3)
    at DestroyableTransform.Transform._read (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at write (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
    at emitReadable_ (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:145:32)
    at afterTransform (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:101:12)
    at TransformState.afterTransform (C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at C:\Users\syuilo\Desktop\projects\misskey\misskey-web\node_modules\vinyl-fs\lib\src\getContents\bufferFile.js:12:5
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:415:3)
```

**Comment by Panya** [comment]
[Yep](http://stylus-lang.com/try.html#?code=%24theme-color%20%3D%20%23f76d6c%0Abody%0A%20%20color%3A%20rgba(%24theme-color%2C%200.7)), make sure that it's a color `#f76d6c` and not a string `'#f76d6c'`.

**Comment by syuilo** [comment]
Thanks for reply!
I have set the following options:
```javascript
rawDefine: {
  '$theme-color': '#f76d6c',
  '$theme-color-foreground': '#fff'
}
```
Am I wrong?

**Comment by Panya** [comment]
`rawDefine` doesn't cast strings to colors. You can use `convert` or `json` bifs for that.

**Comment by syuilo** [comment]
Cool! Thank you very much!
