### ISSUE TITLE
Stylus JS API `linenos` error changes source folder path

### ISSUE THREAD

**Issue by bmcminn** [stylus/stylus#2280]
OS: Win7 Pro 64-bit 
Stylus version: `^0.54.5`
-----

Related: #2279 

-----

The Stylus CLI documentation specifies `linenos` as the appropriate boolean boolean to trigger line number generation: http://stylus-lang.com/docs/executable.html

Internally, the `src/render.js` file uses an `option.lineno` property; and when I use `linenos` as is used elsewhere (including the `/bin/stylus` utility script) causes a problem where my render source paths is rewritten to `process.cwd()/stylus`.

Changing the parameter to `lineno` fixes the issue, but I will reference #2279 why that is another issue.

```
{ Error: stylus:80:1
   76|
   77|
   78|
   79| @import "_timeline"
   80|
-------^
   81|

ENOENT: no such file or directory, realpath 'E:\PROJECT_PATH\stylus'

  at Error (native)
  at Object.realpathSync (fs.js:1568:18)
  at Compiler.debugInfo (E:\PROJECT_PATH\node_modules\stylus\lib\visitor\compiler.js:550:54)
  at Compiler.visitRoot (E:\PROJECT_PATH\node_modules\stylus\lib\visitor\compiler.js:102:44)
  at Compiler.Visitor.visit (E:\PROJECT_PATH\node_modules\stylus\lib\visitor\index.js:28:40)
  at Compiler.compile (E:\PROJECT_PATH\node_modules\stylus\lib\visitor\compiler.js:52:15)
  at Renderer.render (E:\PROJECT_PATH\node_modules\stylus\lib\renderer.js:96:24)
  at E:\PROJECT_PATH\src\index.js:125:10
  at arrayEach (E:\PROJECT_PATH\node_modules\lodash\lodash.js:537:11)
  at Function.forEach (E:\PROJECT_PATH\node_modules\lodash\lodash.js:9359:14)
  at Object.<anonymous> (E:\PROJECT_PATH\src\index.js:111:3)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:456:32)
  at tryModuleLoad (module.js:415:12)
  at Function.Module._load (module.js:407:3)
  at Function.Module.runMain (module.js:575:10)
  at startup (node.js:159:18)
  at node.js:444:3

  errno: -4058,
  code: 'ENOENT',
  syscall: 'realpath',
  path: 'E:\\PROJECT_PATH\\stylus' }
{ Error: stylus:390:1
   386|
   387| ::-webkit-file-upload-button
   388|     -webkit-appearance button             // 1
   389|     font inherit                          // 2
   390|
--------^
```

**Comment by Panya** [comment]
Hmm, can you show the code that you're using? Seems like you don't set `filename` option.

**Comment by bmcminn** [comment]
Just updated my initial comment with a source sample. Going to try setting the `filename`, though I find it wierd I can pass a content string to the `stylus` instance and this one parameter causes this error when using `linenos`.

The snippet I added works perfectly when `linenos` is `false`, but when set to `true`, the above error shows up.

**Comment by bmcminn** [comment]
Ok, setting a `filename` property works, but I still think this is a really strange requirement that I think should be documented in the JS API section.
