### ISSUE TITLE
indent/outdent error not informative enough

### ISSUE THREAD

**Issue by acidjazz** [stylus/stylus#2303]
I got an error on a stylus file I get all the time

```
/Users/k/waa/node_modules/stylus/bin/stylus:661
              throw err;
              ^
ParseError: expected "indent", got "outdent"
    at Parser.error (/Users/k/waa/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (/Users/k/waa/node_modules/stylus/lib/parser.js:287:12)
    at Parser.block (/Users/k/waa/node_modules/stylus/lib/parser.js:845:12)
    at Parser.selector (/Users/k/waa/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.property (/Users/k/waa/node_modules/stylus/lib/parser.js:1498:51)
    at Parser.ident (/Users/k/waa/node_modules/stylus/lib/parser.js:1453:25)
    at Parser.stmt (/Users/k/waa/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (/Users/k/waa/node_modules/stylus/lib/parser.js:685:21)
    at Parser.block (/Users/k/waa/node_modules/stylus/lib/parser.js:865:21)
    at Parser.selector (/Users/k/waa/node_modules/stylus/lib/parser.js:1555:24)
```

is there no way to show where in the stylus file this issue is happening? it's a pain sometimes having to hunt this down

here is the actual code to help reproduce it

```stylus
.lower
  background-color darkblue
  padding 60px 0
  > .inner
    width 1200px
    margin auto
    > .section
      float left
      width 400px
      &.title
        > .copy:first-child
          color white
          font h2
          text-decoration none
        > .copy:nth-child(2)
          color grey
          padding 10px 0 0 0
      &.logos
        float right
        &.logo
          background-size contain
          &.logo-naa
            background-image url(~static/logo-naa.png)
```

**Comment by HerringtonDarkholme** [comment]
I thought it should be a bug rather than improvement per doc se. https://github.com/stylus/stylus/blob/dev/docs/error-reporting.md

**Comment by cbaron** [comment]
```/Users/christopherbaron/code/Hazy/node_modules/stylus/bin/stylus:662                                                         
              throw err;                                      
              ^                                               
ParseError: expected "indent", got "eos"                      
    at Parser.error (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/parser.js:259:11)                             
    at Parser.expect (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/parser.js:287:12)                            
    at Parser.block (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/parser.js:845:12)                             
    at Parser.selector (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/parser.js:1555:24)                         
    at Parser.stmt (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/parser.js:797:27)                              
    at Parser.statement (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/parser.js:685:21)                         
    at Parser.parse (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/parser.js:236:25)                             
    at Evaluator.importFile (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/visitor/evaluator.js:78:20)           
    at Evaluator.visitImport (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/visitor/evaluator.js:920:27)         
    at Evaluator.Visitor.visit (/Users/christopherbaron/code/Hazy/node_modules/stylus/lib/visitor/index.js:28:40)```
