### ISSUE TITLE
Help needed: expected "indent", got "outdent"

### ISSUE THREAD

**Issue by ryuran** [stylus/stylus#2336]
Hello, I have currenty a problem to understand what fails it my stylus code, can you help?

# My code
```stylus
$fontface ?= json('../../fontfaces.json', {hash: true})
$fontload ?= 'optional'

for i, $font in $fontface
    @font-face
        fontSrc = ()
        for j, font in $font.src
            push(fontSrc, font)

        font-family $font.family
        font-weight $font.weight
        font-style $font.style
        src unquote(join(', ', fontSrc))
        font-display $fontload

@font-face
    font-family 'ico'
    font-style normal
    src url('../fonts/ico.eot?#iefix') format('embedded-opentype'),
        url('../fonts/ico.woff') format('woff') // @stylint ignore
```

# The json
```json
[{
    "family": "'Open Sans WebFont'",
    "weight": "normal",
    "style": "normal",
    "src":[
        "local('Open Sans Regular')",
        "local('Open-Sans-Regular')",
        "url('../fonts/OpenSans-Regular.woff2') format('woff2')",
        "url('../fonts/OpenSans-Regular.woff') format('woff')"
    ]
},{
    "family": "'Open Sans WebFont'",
    "weight": "normal",
    "style": "italic",
    "src":[
        "local('Open Sans Italic')",
        "local('Open-Sans-Italic')",
        "url('../fonts/OpenSans-Italic.woff2') format('woff2')",
        "url('../fonts/OpenSans-Italic.woff') format('woff')"
    ]
},{
    "family": "'Open Sans WebFont'",
    "weight": "bold",
    "style": "normal",
    "src": [
        "local('Open Sans Bold')",
        "local('Open-Sans-Bold')",
        "url('../fonts/OpenSans-Bold.woff2') format('woff2')",
        "url('../fonts/OpenSans-Bold.woff') format('woff')"
    ]
},{
    "family": "'Open Sans WebFont'",
    "weight": "bold",
    "style": "italic",
    "src": [
        "local('Open Sans Bold Italic')",
        "local('Open-Sans-Bold-Italic')",
        "url('../fonts/OpenSans-BoldItalic.woff2') format('woff2')",
        "url('../fonts/OpenSans-BoldItalic.woff') format('woff')"
    ]
},{
    "family": "'Open Sans WebFont'",
    "weight": 900,
    "style": "normal",
    "src": [
        "local(:'Open Sans ExtraBold')",
        "local('Open-Sans-ExtraBold')",
        "url('../fonts/OpenSans-ExtraBold.woff2') format('woff2')",
        "url('../fonts/OpenSans-ExtraBold.woff') format('woff')"
    ]
}]
```

# Error
```
…/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		^
ParseError: …/assets/styl/_base/_fonts.styl:36:1
   32|     font-family 'ico'
   33|     font-style normal
   34|     src url('../fonts/ico.eot?#iefix') format('embedded-opentype'),
   35|         url('../fonts/ico.woff') format('woff') // @stylint ignore
   36|
-------^

expected "indent", got "outdent"

    at Parser.error (…/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (…/node_modules/stylus/lib/parser.js:287:12)
    at Parser.block (…/node_modules/stylus/lib/parser.js:845:12)
    at Parser.selector (…/node_modules/stylus/lib/parser.js:1555:24)
    at Parser.property (…/node_modules/stylus/lib/parser.js:1498:51)
    at Parser.ident (…/node_modules/stylus/lib/parser.js:1453:25)
    at Parser.stmt (…/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (…/node_modules/stylus/lib/parser.js:685:21)
    at Parser.block (…/node_modules/stylus/lib/parser.js:865:21)
    at Parser.atrule (…/node_modules/stylus/lib/parser.js:1003:25)
    at Parser.stmt (…/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (…/node_modules/stylus/lib/parser.js:685:21)
    at Parser.block (…/node_modules/stylus/lib/parser.js:865:21)
    at Parser.for (…/node_modules/stylus/lib/parser.js:910:23)
    at Parser.stmt (…/node_modules/stylus/lib/parser.js:778:26)
    at Parser.statement (…/node_modules/stylus/lib/parser.js:685:21)
```

**Comment by Panya** [comment]
You should write `:` when you use a hash value as a property value. E.g.:
```styl
for i, $font in $fontface
    @font-face
        fontSrc = ()
        for j, font in $font.src
            push(fontSrc, font)

        font-family: $font.family
        font-weight: $font.weight
        font-style: $font.style
        src unquote(join(', ', fontSrc))
        font-display $fontload

```

**Comment by ryuran** [comment]
Thank you very much @Panya !
I didn't find anything about it in the documentation.
http://stylus-lang.com/docs/hashes.html
