### ISSUE TITLE
Inline sourcemapping error

### ISSUE THREAD

**Issue by mehmetb** [stylus/stylus#2370]
Hi,

I was testing stylus with a sample code but when I try to run the script stylus throws an error.

Here is the code I was using:

```javascript
const fs = require('fs');
const path = require('path');
const stylus = require('stylus');

fs.readFile(path.join(__dirname, 'example.styl'), 'utf8', (err, styl) => {
  if (err) throw err;

  const style = stylus(styl).set('sourcemap', {inline: true});

  style.render((err, css) => {
    if (err) {
      console.trace(err);
      process.exit(1);
    }
    console.log(css);
  });
});
```

Here is the example.styl:

```stylus
html, body
  padding 0
  margin 0

body
  p
    bacground red
  .dot-selector
    font-family Arial, Helvetica, sans-serif
    font-size 16px

div {
  color: 'black';
}
```

The Error:

```
Trace: { Error: stylus:15:1
   11| 
   12| div {
   13|   color: 'black';
   14| }
   15| 
-------^

ENOENT: no such file or directory, open 'stylus'

    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at SourceMapper.out (/home/user/development/stylus-test/node_modules/stylus/lib/visitor/sourcemapper.js:115:46)
    at SourceMapper.Compiler.visitGroup (/home/user/development/stylus-test/node_modules/stylus/lib/visitor/compiler.js:441:26)
    at SourceMapper.Visitor.visit (/home/user/development/stylus-test/node_modules/stylus/lib/visitor/index.js:28:40)
    at SourceMapper.Compiler.visitRoot (/home/user/development/stylus-test/node_modules/stylus/lib/visitor/compiler.js:103:20)
    at SourceMapper.Visitor.visit (/home/user/development/stylus-test/node_modules/stylus/lib/visitor/index.js:28:40)
    at SourceMapper.Compiler.compile (/home/user/development/stylus-test/node_modules/stylus/lib/visitor/compiler.js:52:15)
    at SourceMapper.compile (/home/user/development/stylus-test/node_modules/stylus/lib/visitor/sourcemapper.js:71:21)
    at Renderer.render (/home/user/development/stylus-test/node_modules/stylus/lib/renderer.js:96:24) errno: -2, code: 'ENOENT', syscall: 'open', path: 'stylus' }
    at style.render (/home/user/development/stylus-test/index.js:12:15)
    at Renderer.render (/home/user/development/stylus-test/node_modules/stylus/lib/renderer.js:107:12)
    at fs.readFile (/home/user/development/stylus-test/index.js:10:9)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

Environment Information

OS: Ubuntu 16.04.4 x86_64 LTS with 4.13.0-37-generic kernel
Node Version: 8.10.0
NPM Version: 5.7.1
Stylus Version: 0.54.5

**Note:** I haven't installed stylus package globally. It is in the local *node_modules* folder as a dev dependency.

**Comment by Panya** [comment]
You need to set `filename` option with a path to the file (to correcly resolve paths to source files in the sourcemap):
```js
const fs = require('fs');
const path = require('path');
const stylus = require('stylus');

const filePath = path.join(__dirname, 'example.styl');

fs.readFile(filePath, 'utf8', (err, styl) => {
  if (err) throw err;

  const style = stylus(styl).set('sourcemap', {inline: true}).set('filename', filePath);

  style.render((err, css) => {
    if (err) {
      console.trace(err);
      process.exit(1);
    }
    console.log(css);
  });
});
```
