### ISSUE TITLE
Background shorthand with position x and y set with calc fails to parse

### ISSUE THREAD

**Issue by CyberAP** [stylus/stylus#2457]
```javascript
stylus.render(`
  .a {
    background: 
      url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3e%3cpath fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right 0.75rem center/8px 10px, 
      url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3e%3cpath fill='%2328a745' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3e%3c/svg%3e") #fff no-repeat center right 1.75rem/calc(0.75em + 0.375rem) calc(0.75em + 0.375rem); 
  }
`)
```

This code would fail with an error:
```
{ ParseError: stylus:1:534
   1| .a { background: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3e%3cpath fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right 0.75rem center/8px 10px, url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3e%3cpath fill='%2328a745' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3e%3c/svg%3e") #fff no-repeat center right 1.75rem/calc(0.75em + 0.375rem) calc(0.75em + 0.375rem); }
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^

expected ")", got ";"

    at Parser.error (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:259:11)
    at Parser.expect (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:287:12)
    at Parser.functionCall (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:1716:10)
    at Parser.primary (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:2178:18)
    at Parser.member (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:2070:21)
    at Parser.subscript (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:2048:21)
    at Parser.unary (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:2039:17)
    at Parser.defined (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:2011:21)
    at Parser.multiplicative (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:1985:21)
    at Parser.additive (C:\Users\CyberAP\Desktop\benchmark\node_modules\stylus\lib\parser.js:1970:21)
  name: 'ParseError',
  message:
   'stylus:1:534\n   1| .a { background: url("data:image/svg+xml,%3csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 4 5\'%3e%3cpath fill=\'%23343a40\' d=\'M2 0L0 2h4zm0 5L0 3h4z\'/%3e%3c/svg%3e") no-repeat right 0.75rem center/8px 10px, url("data:image/svg+xml,%3csvg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 8 8\'%3e%3cpath fill=\'%2328a745\' d=\'M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z\'/%3e%3c/svg%3e") #fff no-repeat center right 1.75rem/calc(0.75em + 0.375rem) calc(0.75em + 0.375rem); }\n-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n\nexpected ")", got ";"\n' }
```

**Comment by xdan** [comment]
What would you like from this code in normal css?
`1.75rem/calc(0.75em + 0.375rem)`
replace to calc(1.75rem / (0.75em + 0.375rem)) will work

**Comment by CyberAP** [comment]
`1.75rem/calc(0.75em + 0.375rem)` is a shorthand to define `background-position` and `background-size`  and is a completely valid CSS.

**Comment by juliencoppry** [comment]
Stylus behaves weirdly when it comes to / operator.
The docs (http://stylus-lang.com/docs/operators.html#multiplicative---) say:
> When using / within a property value, you must wrap with parens. Otherwise the / is taken literally (to support CSS line-height)

The problem is that whenever you use numbers around the / it's considered an operation whether you use parens or not. A simple workaround would be to use a \ in front of your /.
In the end your code would look like this.

```
stylus.render(`
  .a {
    background: 
      url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 4 5'%3e%3cpath fill='%23343a40' d='M2 0L0 2h4zm0 5L0 3h4z'/%3e%3c/svg%3e") no-repeat right 0.75rem center\/8px 10px, 
      url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3e%3cpath fill='%2328a745' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3e%3c/svg%3e") #fff no-repeat center right 1.75rem\/calc(0.75em + 0.375rem) calc(0.75em + 0.375rem); 
  }
`)
```
