### ISSUE TITLE
NodeJS 14 warnings

### ISSUE THREAD

**Issue by real-artswan** [stylus/stylus#2534]
Importing it as 
`import stylus from 'stylus';`
I get warnings on starting the app
```
(node:3446) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3446) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:3446) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:3446) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:3446) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:3446) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
```

Here is the same with --trace-warnings
```
(node:3520) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/node.js:44:23)
    at new Boolean (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:3520) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/node.js:45:23)
    at new Boolean (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:3520) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/node.js:46:25)
    at new Boolean (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:3520) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/node.js:44:23)
    at new Boolean (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:3520) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/node.js:45:23)
    at new Boolean (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:3520) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/node.js:46:25)
    at new Boolean (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/home/artem/DEVELOPMENT/pss2/pss2-backend/node_modules/stylus/lib/nodes/index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
```

**Comment by doberkofler** [comment]
It would be nice, if this small but annoying issue could be resolved

**Comment by Dikman** [comment]
Yes. I agree. I also have such the error in an Angular project. When I try to make a library like in "[Creating libraries](https://angular.io/guide/creating-libraries#getting-started)". I.e.

```
npm install -g @angular/cli
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib
ng build my-lib
```

It is annoying warnings.
```
Building Angular Package
(node:16784) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (C:\444\node_modules\stylus\lib\nodes\node.js:44:23)
    at new Boolean (C:\444\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (C:\444\node_modules\stylus\lib\nodes\index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:16784) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (C:\444\node_modules\stylus\lib\nodes\node.js:45:23)
    at new Boolean (C:\444\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (C:\444\node_modules\stylus\lib\nodes\index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:16784) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (C:\444\node_modules\stylus\lib\nodes\node.js:46:25)
    at new Boolean (C:\444\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (C:\444\node_modules\stylus\lib\nodes\index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:16784) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (C:\444\node_modules\stylus\lib\nodes\node.js:44:23)
    at new Boolean (C:\444\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (C:\444\node_modules\stylus\lib\nodes\index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:16784) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (C:\444\node_modules\stylus\lib\nodes\node.js:45:23)
    at new Boolean (C:\444\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (C:\444\node_modules\stylus\lib\nodes\index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
(node:16784) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:817:11)
    at Object.get (internal/modules/cjs/loader.js:831:5)
    at Boolean.Node [as constructor] (C:\444\node_modules\stylus\lib\nodes\node.js:46:25)
    at new Boolean (C:\444\node_modules\stylus\lib\nodes\boolean.js:23:8)
    at Object.<anonymous> (C:\444\node_modules\stylus\lib\nodes\index.js:58:17)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
```

**Comment by slightlyfaulty** [comment]
If you're using [stylus-loader](https://github.com/shama/stylus-loader) in Webpack, you can use my [stylus-native-loader](https://github.com/slightlyfaulty/stylus-native-loader) instead to suppress these warnings for the time being.

See: https://github.com/slightlyfaulty/stylus-native-loader#stylus-warnings-since-node-v14

**Comment by st-a** [comment]
The issue was fixed by #2538. Current stylus 0.54.8 does not display these warnings anymore.

**Comment by markfswe** [comment]
@real-artswan so this is issue may be closed now I guess?

**Comment by real-artswan** [comment]
> @real-artswan so this is issue may be closed now I guess?

I can confirm that 0.54.8 does not display these warnings anymore
