### ISSUE TITLE
Stylus gives an error in Electron only in production on Linux

### ISSUE THREAD

**Issue by amanharwara** [stylus/stylus#2544]
I use Stylus in my app ([link to app](https://github.com/amanharwara/atlus)) to render a stylus-lang file into CSS.
This works as intended on all platforms, except for Linux where it only works during development but causes an error once the app is packaged.

Here is the terminal output of the error:
```
Error: stylus:4264:1
   4260|             }
   4261|         }
   4262|     }
   4263| }
   4264| }
---------^

Invalid package tmp/.mount_Altus-itqVL2/resources/app.asar

    at createError (electron/js2c/asar.js:126:17)
    at Object.fs.readFileSync (electron/js2c/asar.js:545:27)
    at Evaluator.importFile (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/evaluator.js:48:16)
    at Evaluator.visitImport (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/evaluator.js:920:27)
    at Evaluator.Visitor.visit (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitRoot (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at Evaluator.Visitor.visit (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.evaluate (/tmp/.mount_Altus-itqVL2/resources/app.asar/node_modules/stylus/lib/visitor/evaluator.js:247:15) {
  lineno: 4264,
  column: 1,
  filename: 'stylus',
  stylusStack: ''
}
```

This error does not give any information that I can use to debug this. And I know that there is no issue in the actual style because it works fine on every other platform.

Please let me know if you have any idea why this might be happening.

**Comment by pakastin** [comment]
Electron packages your app in app.asar file, so it's an Electron issue..
