### ISSUE TITLE
Nothing works - LOCK File currently in use

### ISSUE THREAD

**Issue by mwisnicki** [stylus/stylus#2654]
Stylus 1.5.22
Chrome Version 97.0.4692.99 (Official Build) (64-bit)

The extension does not work - it lost all the styles and none of the UI on management page works - everything is empty and buttons do nothing.

There are some errors reported in the console:
```
Uncaught (in promise) Error: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
    at polyfill.js:32:20
manage.js:99 Uncaught (in promise) Error: IO error: .../LOCK: File currently in use. (ChromeMethodBFE: 15::LockFile::2)
    at polyfill.js:32:20
```

**Comment by mwisnicki** [comment]
Reinstalling extension didn't help but switching to beta (which has the same version) did.

**Comment by mwisnicki** [comment]
Sorry, it's just Options, Import, Export, Sync buttons that do nothing.

**Comment by mwisnicki** [comment]
Nevermind, this seems to be some Windows/Chrome issue https://bugs.chromium.org/p/chromium/issues/detail?id=490915
