### ISSUE TITLE
Server Side Error in Next JS API Route

### ISSUE THREAD

**Issue by petermarks12** [stylus/stylus#2711]
For some reason, I am getting following error only on my server, but not in development.  Can somebody tell me, why it is happening?

> Error: stylus:16:4
>    12|   form buttton {
>    13|     padding: 25px;
>    14|     border: 10px solid;
>    15|     border-radius: 50%;
>    16|   }
> ----------^
> failed to locate @import file /var/task/node_modules/stylus/lib/functions/index.styl
>     at Evaluator.visitImport (/var/task/node_modules/stylus/lib/visitor/evaluator.js:915:21)
>     at Evaluator.Visitor.visit (/var/task/node_modules/stylus/lib/visitor/index.js:28:40)
>     at Evaluator.visit (/var/task/node_modules/stylus/lib/visitor/evaluator.js:160:18)
>     at Evaluator.visitRoot (/var/task/node_modules/stylus/lib/visitor/evaluator.js:707:27)
>     at Evaluator.Visitor.visit (/var/task/node_modules/stylus/lib/visitor/index.js:28:40)
>     at Evaluator.visit (/var/task/node_modules/stylus/lib/visitor/evaluator.js:160:18)
>     at Evaluator.evaluate (/var/task/node_modules/stylus/lib/visitor/evaluator.js:247:15)
>     at Renderer.render (/var/task/node_modules/stylus/lib/renderer.js:86:26)
>     at Function.exports.render (/var/task/node_modules/stylus/lib/stylus.js:82:37)
>     at result (/var/task/.next/server/pages/api/[slug].js:25384:35) {
>   lineno: 16,
>   column: 4,
>   filename: 'stylus',
>   stylusStack: ''
> }

**Comment by iChenLei** [comment]
@petermarks12 Hi, I am confused. Why you need compile `.styl` on the server ? A normal usage is compile `.styl` to `.css` at dev time, and hositing css files at sevrer (or cdn).

**Comment by petermarks12** [comment]
I am working on a hobby project to convert stylus code to css.  User will provide stylus code.  Application will compile and display CSS.
