### ISSUE TITLE
Environment dependent "Maximum call stack size exceeded" error

### ISSUE THREAD

**Issue by TokugawaTakeshi** [stylus/stylus#2732]
Recently, I have open the issue ["Maximum call stack size exceeded" error on calling the Stylus mixin from the library while without Vite working fine](https://github.com/vitejs/vite/issues/10605) in the Vite repostiory. In [my reproduction](https://github.com/TokugawaTakeshi/Issue-ViteStylusMixins) , I have made the experiment with plain Stylus and it works, and the expetiment with the Vite and it emits the error. I was completely sure that the Vite was the cause, however, the Vite maintainer has created the [another reproduction](https://stackblitz.com/edit/node-buhnjw?file=index.js), with Stylus only.

As result: same code could work or not work under uncertain combination of circumstances, however, we have both working and not working reproductions.

**To reproduce:**

Check this repros:

* [Working plain Stylus + not working Vite reproduction](https://github.com/TokugawaTakeshi/Issue-ViteStylusMixins)
* [Not working Stylus reproduction](https://stackblitz.com/edit/node-buhnjw?file=index.js)

**Current behavior:**

Emits "Maximum call stack size exceeded" error in some enviroments.

**Expected behavior:**

Works correctly in all envirinments.

**Environment information:**

- `stylus` version: 0.59.0
- `nodejs` version: v16.13.0

**Additional information:**

The [Paddings](https://github.com/TokugawaTakeshi/Yamato-Daiwa-Frontend/blob/master/CoreLibrary/Package/Styles/02-Kernel/03-UtilityMixins/01-Sizing/04-Paddings.styl) mixin calls the [validateObjectTypeParameter](https://github.com/TokugawaTakeshi/Yamato-Daiwa-Frontend/blob/master/CoreLibrary/Package/Styles/02-Kernel/02-Functions/06-ParametersValidation/validateObjectTypeParameter.styl) function.  It calls the internal `validateSpecificDepthLevelOfTargetObjectTypeParameter` function recursively (for the validation of nested objects), and normally, it works fine .

Please feel free to ask me anything about `Paddings`, `validateObjectTypeParameter` and other functionality of [@yamato-daiwa/frontend](https://github.com/TokugawaTakeshi/Yamato-Daiwa-Frontend/blob/master/CoreLibrary/Package/README.md).

**Comment by TokugawaTakeshi** [comment]
Got new details about this issue.

It was previously known that the occurrence location is `stylus\lib\visitor\deps-resolver` but looks like this error will *not* prevent the CSS code from beenoutput.

Consider the simple example:

```js
import stylus from "stylus";

const content = `
@require "Functionality.styl"

.Test

  p("Checkpoint A")

  fillBodyVertically({ verticalScrolling: false })
  
  p("Checkpoint B")
`;

const ref = stylus(content, {});
ref.render();
ref.deps();
```

Although the `fillBodyVertically` causes the error, the `"Checkpoint B"` has been reached!

> <img width="1217" height="449" alt="Image" src="https://github.com/user-attachments/assets/d34fcac6-3cba-49a6-bc7c-6939f2d23899" />
> 
> ```
> "C:\Program Files\nodejs\node.exe" D:\NNN\errorRepro.mjs
> inspect: "Checkpoint A"
> inspect: "Checkpoint B"
> D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:34
>   visit(node) {
>        ^
> 
> RangeError: stylus:undefined:undefined
> 
> 
> Maximum call stack size exceeded
> 
>     at DepsResolver.visit (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:34:8)
>     at DepsResolver.visitRoot (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:61:12)
>     at DepsResolver.visit (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:39:14)
>     at DepsResolver.visitRoot (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:61:12)
>     at DepsResolver.visit (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:39:14)
>     at DepsResolver.visitIf (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:78:10)
>     at DepsResolver.visit (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\index.js:29:42)
>     at DepsResolver.visit (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:51:15)
>     at DepsResolver.visitRoot (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:61:12)
>     at DepsResolver.visit (D:\WebDevelopmentProjects\InHouseDevelopment\YamatoDaiwaFrontend\CoreLibrary\Package\node_modules\stylus\lib\visitor\deps-resolver.js:39:14)
> 
> Node.js v22.15.0
> 
> Process finished with exit code 1
> ```

But the error has been caused by `validateObjectTypeParameter` function which `fillBodyVertically` uses, not by `fillBodyVertically` itself. The implementation of `validateObjectTypeParameter`  is:

```stylus
validateObjectTypeParameter(namedParameters)

  mixinOrFunctionName = namedParameters.mixinOrFunctionName

  if !isNonEmptyString(mixinOrFunctionName) {
    error(
      "Please specify the property 'mixinOfFunctionName' at first and only object-type parameter of function " +\
      "'validateObjectTypeParameter' with non-empty string for clear logging where exactly error could occur."
    )
  }


  targetParameterNumber = namedParameters.targetParameterNumber

  if !isNaturalNumber(targetParameterNumber)
    error(
      "Please specify the property 'targetParameterNumber' at first and only object-type parameter of function " +\
      "'validateObjectTypeParameter' with natural number for clear logging what number parameter is invalid."
    )


  schema = namedParameters.schema

  if !isObject(schema)
    error(
      "Please specify the property 'schema' at first and only object-type parameter of function " +\
      "'validateObjectTypeParameter' with object describing the scema of valid target parameter to display it to " +\
      "user if invalid value will be passed."
    )


  // [ Theory ] Explicit null will not be substituted by Stylus default parameters functionality
  targetParameter = nullToEmptyObject(namedParameters.targetParameter)

  if (!isObject(targetParameter)) {
    error(buildString(
      "The parameter number ${targetParameterNumber} of function/mixin '${mixinOrFunctionName}' must be of object type.\n" +\
      "Actual value: ${actualValue}\n" +\
      "Actual value's type: ${actualValueType}\n" +\
      "Please check this parameter's schema:\n${schema}",
      {
        targetParameterNumber: targetParameterNumber,
        mixinOrFunctionName: mixinOrFunctionName,
        actualValue: targetParameter,
        actualValueType: typeof(targetParameter),
        schema: formatObject(schema)
      }
    ))
  }


  followingParametersWhichMustNotBe = namedParameters.followingParametersWhichMustNotBe

  if isNotNull(followingParametersWhichMustNotBe) {
    error(buildString(
      "The function/mixin '${mixinOrFunctionName}' must NOT have more than ${lastParameterNumber} parameters.\n" +\
      "Please check this parameter's schema:\n${schema}",
      {
        mixinOrFunctionName: mixinOrFunctionName,
        lastParameterNumber: targetParameterNumber,
        schema: formatObject(schema)
      }
    ))
  }


  generateErrorMessage(templateParameters)

    return buildString(
      "Invalid parameter at:" +\
      "\n  ●  Function/mixin: ${mixinOrFunctionName}" +\
      "\n  ●  Parameter number: ${targetParameterNumber}" +\
      "\n  ●  Parameter's property: ${parameterPropertyPath}" +\
      "\n${messageSpecificPart}" +\
      "\nPlease check the specification of this property: \n${propertyFormattedSpecification}",
      {
        mixinOrFunctionName: mixinOrFunctionName,
        targetParameterNumber: targetParameterNumber,
        parameterPropertyPath: templateParameters.parameterPropertyPath
        messageSpecificPart: templateParameters.messageSpecificPart,
        propertyFormattedSpecification: formatObject(templateParameters.propertySpecification)
      }
    )


  // [ Stylus theory ] If just prepare the string-type variable here like
  // targetParameterCurrentPropertyDotSeparatedPath = ""
  // it's value will reset to "" on each invocation of "validateSpecificDepthLevelOfTargetObjectTypeParameter"
  targetParameterCurrentPropertyDotSeparatedPathValueHolder = { value: "" }

  // [ Warning ] Skipping of curly brackets will cause 'unexpected "else"' error (possible Stylus bug)
  validateSpecificDepthLevelOfTargetObjectTypeParameter(objectOfCurrentLevel, levelSchema) {

    for propertyName, propertySpecification in levelSchema {

      targetParameterCurrentPropertyDotSeparatedPathValueHolder.value =\
          isEmptyString(targetParameterCurrentPropertyDotSeparatedPathValueHolder.value) ?\
          propertyName : targetParameterCurrentPropertyDotSeparatedPathValueHolder.value + "." + propertyName

      propertyValue = objectOfCurrentLevel[propertyName]

      if (isNull(propertyValue)) {

        if (propertySpecification.required) {
          error(generateErrorMessage({
            messageSpecificPart: "This property is required while actually has been omited or explicitly set to null."
            parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
            propertySpecification: propertySpecification
          }))
        }


        if (isNotNull(propertySpecification.requiredIf)) {

          // [ Stylus theory ] Functions in objects could be called if and only if destructured
          predicate = propertySpecification.requiredIf.predicate

          if (isTrue(predicate(objectOfCurrentLevel, targetParameter))) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This property is required when ${requirementConditionDescription} and this condition has been satisfied " +\
                "while this proeprty has been omited or explicitly set to null.",
                { requirementConditionDescription:  propertySpecification.requiredIf.conditionDescription }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }
        }


        if (isNotNull(propertySpecification.defaultValue)) {
          targetParameter[propertyName] = propertySpecification.defaultValue
        }

        // [ Stylus theory ] Even if add "return" here, the execution will continue after "if-else" block
      } else {

        if (isNotNull(propertySpecification.incompatibleWith)) {
          for incompatiblePropertyDotSeparatedPath in propertySpecification.incompatibleWith {
            if (isNotNull(getObjectValueByDotSeparatedPathSafely(targetParameter, incompatiblePropertyDotSeparatedPath))) {
              error(generateErrorMessage({
                messageSpecificPart: buildString(
                  "This property is incompatible with property '${incompatiblePropertyDotSeparatedPath}'.",
                  { incompatiblePropertyDotSeparatedPath: incompatiblePropertyDotSeparatedPath }
                ),
                parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
                propertySpecification: propertySpecification
              }))
            }
          }
        }


        if (!isNonEmptyString(propertySpecification.type)) {
          error(buildString(
            "No valid type has been specified for the property ${propertyName} - it must be the non-empty string, " +\
            "the element of 'DataTypes--YDF' enumeration, while actual value is ${actualValue}.",
            {
              propertyName: propertyName,
              actualValue: propertySpecification.type
            }
          ))
        }


        // --- String --------------------------------------------------------------------------------------------------
        if (propertySpecification.type == DataTypes--YDF.string) {

          if (isTrue(propertySpecification.considerIdentifierAsString)) {
            propertyValue = "" + propertyValue
          }

          if (!isString(propertyValue)) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This property must be the string while actually has type '${propertyActualType}' and value '${propertyValue}'.",
                {
                  propertyActualType: typeof(propertyValue),
                  propertyValue: propertyValue
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }

          if (
            isNotNull(propertySpecification.minimalCharactersCount) &&\
            length(propertyValue) < propertySpecification.minimalCharactersCount
          ) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This string-type property has ${actualCharactersCount} characters while at least " +\
                "${minimalCharactersCount} required.",
                {
                  actualCharactersCount: length(propertyValue),
                  minimalCharactersCount: propertySpecification.minimalCharactersCount
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }

          if (
            isNotNull(propertySpecification.maximalCharactersCount) &&\
            length(propertyValue) > propertySpecification.maximalCharactersCount
          ) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This string-type property has ${actualCharactersCount} characters while ${maximalCharactersCount} " +\
                "allowed as maximum.",
                {
                  actualCharactersCount: length(propertyValue),
                  maximalCharactersCount: propertySpecification.maximalCharactersCount
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }

          if (\
            isNotNull(propertySpecification.allowedAlternatives) &&\
            !hasPrimitivesArraySpecifiedElement(propertySpecification.allowedAlternatives, propertyValue)
          ) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This string-type property has value '${actualValue}' while below alternatives only allowed:\n" +\
                "${formattedAllowedAlternatives}",
                {
                  actualValue: propertyValue,
                  formattedAllowedAlternatives: join(", ", propertySpecification.allowedAlternatives)
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }

        } else if (
          propertySpecification.type[0] == DataTypes--YDF.dimensionalQuantity ||\
          propertySpecification.type[0] == DataTypes--YDF.dimensionlessQuantity
        ) {

          if (
            propertySpecification.type[0] == DataTypes--YDF.dimensionalQuantity &&\
            propertySpecification.type[1] == DataTypes--YDF.dimensionlessQuantity
          ) {

            // --- Dimensional or dimensionless amount -----------------------------------------------------------------
            if (!isDimensionalOrDimensionlessQuantity(propertyValue)) {
              error(generateErrorMessage({
                messageSpecificPart: buildString(
                  "This property must be either dimensional or dimensionless amount while actually has type " +\
                  "'${propertyActualType}' and value '${propertyValue}'.",
                  {
                    propertyActualType: typeof(propertyValue),
                    propertyValue: propertyValue
                  }
                ),
                parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
                propertySpecification: propertySpecification
              }))
            }

          } else if (propertySpecification.type == DataTypes--YDF.dimensionalQuantity) {

            // --- Dimensional amount ----------------------------------------------------------------------------------

            // [ Stylus theory ] Direct usage if below expression in "if" statement will cause the Stylus bug
            // expected ")", got "{"
            hasValueDimensionalAmountType = isDimensionalQuantity(propertyValue, "MUST_CONSIDER_DIMENSIONLESS_ZERO_AS_DIMENSIONAL_QUANTITY")

            if (!hasValueDimensionalAmountType) {

              if (typeof(propertyValue) == "unit") {

                error(generateErrorMessage({
                  messageSpecificPart: "This property must have the units while actually is dimensionless.",
                  parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
                  propertySpecification: propertySpecification
                }))

              } else {

                error(generateErrorMessage({
                  messageSpecificPart: buildString(
                    "This property must be the dimensional amount while actually has type '${propertyActualType}' and value '${propertyValue}'.",
                    {
                      propertyActualType: typeof(propertyValue),
                      propertyValue: propertyValue
                    }
                  ),
                  parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
                  propertySpecification: propertySpecification
                }))

              }
            }

          } else if (propertySpecification.type == DataTypes--YDF.dimensionlessQuantity) {

            // --- Dimensionless amount --------------------------------------------------------------------------------
            if (!isDimensionlessQuantity(propertyValue)) {

              if (typeof(propertyValue) == "unit") {

                error(generateErrorMessage({
                  messageSpecificPart: "This property must not have the units while actually is dimensional.",
                  parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
                  propertySpecification: propertySpecification
                }))

              } else {

                error(generateErrorMessage({
                  messageSpecificPart: buildString(
                    "This property must be the dimensionless amount while actually has type '${propertyActualType}' and value '${propertyValue}'.",
                    {
                      propertyActualType: typeof(propertyValue),
                      propertyValue: propertyValue
                    }
                  ),
                  parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
                  propertySpecification: propertySpecification
                }))

              }
            }
          }


          if (
            isDimensionlessQuantity(propertySpecification.minimalValue) &&\
            propertyValue < propertySpecification.minimalValue
          ) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This amount has value ${actualValue} while minimal allowed value is ${minimalValue}.",
                {
                  actualValue: propertyValue,
                  minimalValue: propertySpecification.minimalValue
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }

          if (
            isDimensionlessQuantity(propertySpecification.maximalValue) &&\
            propertyValue > propertySpecification.maximalValue
          ) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This amount has value '${actualValue}' while maximal allowed value is ${maximalValue}.",
                {
                  actualValue: propertyValue,
                  maximalValue: propertySpecification.maximalValue
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }

        } else if (propertySpecification.type == DataTypes--YDF.boolean) {

          // --- Boolean -----------------------------------------------------------------------------------------------

          if (!isBoolean(propertyValue)) {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This property must be the boolean while actually has type '${propertyActualType}' and value '${propertyValue}'.",
                {
                  propertyActualType: typeof(propertyValue),
                  propertyValue: propertyValue
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }
        } else if (propertySpecification.type == DataTypes--YDF.colorDefinition) {

          // --- Color definition --------------------------------------------------------------------------------------
          if (typeof(propertyValue) != "rgba" && typeof(propertyValue) != "hsla") {
            error(generateErrorMessage({
              messageSpecificPart: buildString(
                "This property must be the color definition while actually has type '${propertyActualType}' and value '${propertyValue}'.",
                {
                  propertyActualType: typeof(propertyValue),
                  propertyValue: propertyValue
                }
              ),
              parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
              propertySpecification: propertySpecification
            }))
          }
        } else if (propertySpecification.type == DataTypes--YDF.object) {

          if (!isObject(propertyValue)) {
            error(buildString(
              "The property '${propertyName}' in parameters object of mixin/function '${mixinOrFunctionName}' must be the " +\
              "object while aclually it has type '${propertyRealType}' and value: ${propertyValue}",
              {
                propertyName: propertyName,
                mixinOrFunctionName: mixinOrFunctionName,
                propertyRealType: typeof(propertyValue),
                propertyValue: propertyValue
              }
            ))
          }

          validateSpecificDepthLevelOfTargetObjectTypeParameter(
            objectOfCurrentLevel: propertyValue,
            levelSchema: propertySpecification.properties
          )
        } else {

          error(generateErrorMessage({
            messageSpecificPart: buildString(
              "The type '${propertyActualType}' is unknown.",
              { propertyActualType: typeof(propertyValue) }
            ),
            parameterPropertyPath: targetParameterCurrentPropertyDotSeparatedPathValueHolder.value,
            propertySpecification: propertySpecification
          }))
        }
      }

      targetParameterCurrentPropertyDotSeparatedPathValueHolder.value = replace(".\w+$", "", targetParameterCurrentPropertyDotSeparatedPathValueHolder.value)
    }
  }


  validateSpecificDepthLevelOfTargetObjectTypeParameter(objectOfCurrentLevel: targetParameter, levelSchema: schema)
```

Although this implementation is large and complicated, if it represents the valid Stylus syntax, this is the case when I have a right to declare it as a bug and ask you to fix this.

Additionally, this error is tool-dependent.

+ **Node.js script + stylus package** (as above example): does occur
+ **Stylus CLI + `.styl` file**:  does _not_ occur
+ **Webpack loader**: does _not_ occur
+ **Vite loader**: [does occur](https://github.com/vitejs/vite/issues/10605)

**Comment by TokugawaTakeshi** [comment]
@iChenLei 

If I'll create the pull request fixing this bug will you merge it and release the newest version of Stylus?
I am fine to collaborate, but I will not waste my strictly limited time if my pull request will be just ignored.
