### ISSUE TITLE
Broken Playground/ runkit can't find `stylus`

### ISSUE THREAD

**Issue by WilNichols** [stylus/stylus#2910]
**To reproduce:**
Visit https://stylus-lang.com/try.html. Press "run"

**Current behavior:**

Runkit can't find `stylus`. 
![Snap 23 02 on 12-05-2024@2x](https://github.com/user-attachments/assets/4abccfd5-d6d8-420f-9be9-954c6e696e7d)

**Expected behavior:**

Runkit finds `stylus`, code builds.

**Environment information:**

- `stylus` version: 61.0
- `nodejs` version: 10

**Comment by Phroneris** [comment]
Currently, the page doesn't even display the “run” button.

<img width="1000" height="540" alt="Image" src="https://github.com/user-attachments/assets/ba556c94-71a2-4ebb-8143-7e10395dcc59" />

DevTools console output by Google Chrome 141.0.7390.55 64-bit:

```
Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]
    at Y.createHandlerBoundToURL (workbox-5d567057.js:1:18565)
    at Object.createHandlerBoundToURL (workbox-5d567057.js:1:21595)
    at sw.js:1:5969
    at sw.js:1:565
```

**Comment by danielbayley** [comment]
Some alternative suggestions:

[npmjs.dev/stylus](https://npmjs.dev/stylus)

[ESM>Playground](https://code.esm.sh)

[CodeSandbox](https://codesandbox.io)

[StackBlitz](https://stackblitz.com)

or even [CodePen](codepen.io) has Stylus…
