### ISSUE TITLE
[Bug] Unable to Export to File

### ISSUE THREAD

**Issue by Nick2bad4u** [stylus/stylus#2912]
**To reproduce:**

Not sure, I think it has to do with my number of styles (over 200). I never had an issue with this before today.

**Current behavior:**

Clicking export, either normal or compatibility does nothing. Checking console shows error in the API.styles.getOrder function.

```
Error:

Uncaught (in promise) Error: Unknown API.styles.getOrder
    at chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/sw.js:1:92280
    at _execute (chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/sw.js:1:12533)
    at MessagePort.onMessage (chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/sw.js:1:93302)
Error
    at exec (chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/js/common.js:1:7007)
    at s.apiHandler.apply (chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/js/common.js:1:4857)
    at HTMLButtonElement.exportToFile (chrome-extension://clngdbkpkpeebahjckkjfobafhncgmne/js/manage-lazy-init.js:1:15339)
```

**Expected behavior:**

Exports settings to a file.

**Environment information:**

- `stylus` version: 2.0.8
- `nodejs` version: Unsure.

Log file from Console: 

[clngdbkpkpeebahjckkjfobafhncgmne-1735084886798.log](https://github.com/user-attachments/files/18242269/clngdbkpkpeebahjckkjfobafhncgmne-1735084886798.log)

Gif:
https://github.com/user-attachments/assets/ae5aaca9-ccd8-4444-bc5a-9de78e79c1ab

**Comment by vendethiel** [comment]
I don't think this is the Stylus repo you're looking for.

**Comment by Nick2bad4u** [comment]
> I don't think this is the Stylus repo you're looking for.

I just noticed that and was about to close it lol. Sorry.
