### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by jasonkuhrt** [stylus/stylus#664]
Stylus:

```
for icon_size in 16 24 32 48 128
  [class^="icon-dark-{icon_size}"]
  [class*=" icon-dark-{icon_size}"]
    &:before
      vertical-align middle
      square(unit(icon_size,px))
      background-image url(/images/sprites/helveticons-additional-dark-{icon_size}.png)
      content ""
```

Error:

```
   249|   background-position 0 0
   250| 
   251| for icon_size in 16 24 32 48 128
   252|   [class^="icon-dark-{icon_size}"]
 > 253|   [class*=" icon-dark-{icon_size}"]
   254|     &:before
   255|       vertical-align middle
   256|       square(unit(icon_size,px))

expected "indent", got "outdent"

    at Parser.error (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:166:11)
    at Parser.expect (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:194:12)
    at Parser.block (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:596:12)
    at Parser.selector (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:1098:24)
    at Parser.stmt (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:562:27)
    at Parser.statement (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:457:21)
    at Parser.block (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:608:21)
    at Parser.for (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:651:23)
    at Parser.stmt (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:545:25)
    at Parser.statement (/Users/KUHRT/code/artfox/node_modules/stylus/lib/parser.js:457:21)
```

Seems like this should compile to me. Any ideas?

**Comment by kizu** [comment]
This would be fixed when we'd implement #728, so I'm closing this as a duplicate.
