### ISSUE TITLE
Using executable from another directory breaks imports

### ISSUE THREAD

**Issue by chiel** [stylus/stylus#757]
Let's say I have two files:
- a.styl
  
  ```
  @import b
  ```
- b.styl
  
  ```
  .something {
    color: red
  }
  ```

If you execute `stylus < file.styl > out.css` it works fine. But let's assume I execute the command from the parent directory, e.g. `stylus < css/file.styl > out.css`, it throws a horrible tantrum which will look something like this:

```
$ stylus < ./ui/src/css/tinker.styl > ./public/tinker.css 

/usr/local/lib/node_modules/stylus/bin/stylus:459
      if (err) throw err;
                     ^
Error: stdin:30
   26| }
   27| 
   28| // @import './region'
   29| @import cell
 > 30| 
   31| // editor container
   32| .editor {
   33|  position: absolute;

failed to locate @import file cell.styl

    at Evaluator.visitImport (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:659:21)
    at Evaluator.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:75:18)
    at Evaluator.visitRoot (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:521:27)
    at Evaluator.Visitor.visit (/usr/local/lib/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:75:18)
    at Evaluator.evaluate (/usr/local/lib/node_modules/stylus/lib/visitor/evaluator.js:150:15)
    at Renderer.render (/usr/local/lib/node_modules/stylus/lib/renderer.js:69:26)
    at null.<anonymous> (/usr/local/lib/node_modules/stylus/bin/stylus:458:11)
    at EventEmitter.emit (events.js:85:17)
```

It cannot find the required file, cause it's looking relative to the directory where the command was executed. In my opinion, it really should be looking for the file relative to the file it is being imported from.

Hope this was clear, if not, please do let me know. :)

**Comment by 1000i100** [comment]
+1
